name: Jekyll site CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    # keep the jobs from running on forks with Actions enabled, as they won't
    # have the appropriate permissions and/or env variables.
    if: github.repository == 'adafruit/circuitpython-org'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Install Dependencies
      run: |
        bundle install
    - name: Build site with jekyll
      run: |
        bundle exec jekyll build -d build
    - name: Commit and Push to gh-pages
      run: |
        # https://github.com/helaili/jekyll-action/blob/master/entrypoint.sh#L49
        cd build
        touch .nojekyll
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'jekyll build from Action'
        git push --force https://${ADABOT_PAT}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
        rm -fr .git
        cd ..
      env:
        ADABOT_PAT: ${{ secrets.ADABOT_PAT }}
